// Word database. Each word: [word, difficulty ('easy'|'medium'|'hard'), [hints...]]
// Hints must never contain the word itself. Kept intentionally vague.

const W = (word, diff, hints) => ({ word, difficulty: diff, hints });

const WORDS = [
  // ===== PLACES =====
  W("beach", "easy", ["Associated with summer.", "People go there to relax.", "Often linked to vacations.", "Connected to warm weather."]),
  W("airport", "easy", ["Associated with travelling.", "People often feel rushed there.", "Linked to long waits.", "People say goodbye there a lot."]),
  W("school", "easy", ["Associated with childhood.", "People spend years of their life there.", "Mornings are connected to it.", "Involves routines and bells."]),
  W("hospital", "easy", ["Associated with emergencies.", "People hope not to end up there.", "Linked to white coats.", "A place of recovery."]),
  W("restaurant", "easy", ["Associated with going out at night.", "People celebrate things there.", "Linked to being served.", "A treat for many people."]),
  W("cinema", "easy", ["Associated with weekends.", "People go there in the dark.", "Snacks are overpriced there.", "People sit quietly for hours there."]),
  W("library", "easy", ["A very quiet place.", "Associated with silence.", "People borrow things there.", "Linked to studying."]),
  W("gym", "easy", ["Associated with New Year's resolutions.", "People sweat there.", "Linked to self-improvement.", "Some people pay monthly but never go."]),
  W("park", "easy", ["Associated with fresh air.", "People walk their pets there.", "Families spend Sundays there.", "An escape within the city."]),
  W("hotel", "easy", ["Associated with travelling.", "People check in and out.", "Someone else makes your bed there.", "Linked to room service."]),
  W("museum", "medium", ["People walk slowly there.", "Associated with hushed voices.", "You look but can't touch.", "A tourist favorite."]),
  W("stadium", "medium", ["Associated with huge crowds.", "People cheer loudly there.", "Beer and chanting come to mind.", "Emotions run high there."]),
  W("casino", "medium", ["Associated with risk.", "People lose money there.", "Flashing lights come to mind.", "Luck decides everything there."]),
  W("zoo", "medium", ["Associated with childhood trips.", "People stare at things behind glass.", "Smells are part of the experience.", "A family day out."]),
  W("circus", "medium", ["Associated with spectacle.", "Something from another era.", "Bright colors and performers.", "Children are amazed there."]),
  W("farm", "medium", ["Associated with early mornings.", "Life there follows the seasons.", "Smells strongly of nature.", "Far from the city."]),
  W("desert", "medium", ["Associated with extremes.", "Few living things survive there.", "Linked to endless horizons.", "Silence dominates it."]),
  W("island", "medium", ["Associated with isolation.", "Surrounded on all sides by the same thing.", "People dream of owning one.", "Linked to castaway stories."]),
  W("volcano", "hard", ["Dormant but dangerous.", "Associated with unpredictable power.", "People live nervously near it.", "It has shaped entire civilizations."]),
  W("junkyard", "hard", ["Where things go when abandoned.", "Associated with rust and decay.", "Treasures are hidden among trash there.", "Linked to endings."]),
  W("rooftop", "hard", ["Above everything else.", "Associated with city views.", "A private escape in a crowded place.", "Where people go to think."]),

  // ===== OBJECTS =====
  W("phone", "easy", ["People can't live without it.", "Associated with constant checking.", "It dies at the worst moments.", "Carried everywhere."]),
  W("laptop", "easy", ["Associated with remote work.", "People take it to coffee shops.", "It gets warm on your lap.", "Opens and closes."]),
  W("umbrella", "easy", ["Only remembered when needed.", "People forget it everywhere.", "Associated with bad weather.", "It turns inside out."]),
  W("backpack", "easy", ["Associated with carrying things daily.", "Students rely on it.", "Straps are involved.", "Travels on your shoulders."]),
  W("mirror", "easy", ["People check it every morning.", "It tells the truth.", "Associated with vanity.", "It reverses everything."]),
  W("camera", "easy", ["Captures memories.", "Associated with special occasions.", "People pose for it.", "It freezes time."]),
  W("watch", "easy", ["Worn on the body.", "Associated with punctuality.", "Often a gift.", "It never stops."]),
  W("bicycle", "easy", ["Two of something.", "Associated with childhood freedom.", "Good exercise is involved.", "Balance is required."]),
  W("pillow", "easy", ["Associated with comfort.", "You use it every night without thinking.", "Fights are had with it.", "Soft and essential."]),
  W("television", "easy", ["The center of most living rooms.", "Associated with binge watching.", "Families argue over it.", "It talks at you for hours."]),
  W("toothbrush", "easy", ["Used twice a day, hopefully.", "Associated with hygiene routines.", "Very personal, never shared.", "Lives in the bathroom."]),
  W("refrigerator", "easy", ["Opened many times a day.", "Associated with midnight snacks.", "People stare into it hoping for something new.", "It hums all day."]),
  W("microwave", "easy", ["For impatient people.", "Associated with leftovers.", "Beeps when finished.", "Speed over quality."]),
  W("keys", "easy", ["Constantly lost.", "Associated with pockets and panic.", "Jingling sound.", "Without them you're stuck."]),
  W("wallet", "easy", ["Associated with pockets.", "People panic when they can't find it.", "Holds your identity.", "Stuffed with useless receipts."]),
  W("headphones", "medium", ["Used to ignore people.", "Associated with commuting.", "A do-not-disturb sign.", "They always tangle or die."]),
  W("drone", "medium", ["Associated with aerial views.", "Controversial in public spaces.", "Linked to modern hobbies.", "People crash them."]),
  W("telescope", "medium", ["Associated with dreams and wonder.", "Used at night.", "Reveals things very far away.", "Linked to childhood ambition."]),
  W("typewriter", "medium", ["A relic of another era.", "Loud and mechanical.", "Associated with old-school writers.", "Every mistake is permanent."]),
  W("chess", "medium", ["Associated with patience.", "Quiet but intense.", "Linked to strategy.", "Old but never boring."]),
  W("guitar", "medium", ["Associated with campfires.", "Many people own one but can't play it.", "Fingers hurt at first.", "A roommate cliché."]),
  W("candle", "medium", ["Associated with ambiance.", "Used when the power goes out.", "Romantic or religious settings.", "It slowly disappears."]),
  W("ladder", "medium", ["Associated with climbing.", "Bad luck involves it somehow.", "Helpful for reaching things.", "Standing under one is supposedly unlucky."]),
  W("chainsaw", "hard", ["Associated with lumberjacks and horror movies.", "Very loud.", "Requires respect.", "Overkill for most tasks."]),
  W("karaoke", "medium", ["Associated with embarrassment.", "Confidence is required.", "Usually involves drinks.", "Everyone thinks they sound better than they do."]),
  W("hourglass", "hard", ["Time made visible.", "Associated with game shows.", "Old-fashioned measurement.", "It runs out."]),
  W("boomerang", "hard", ["It comes back.", "Associated with a distant country.", "Throwing it is an art.", "Most people fail with it."]),
  W("mannequin", "hard", ["Silent observer in stores.", "Slightly unsettling.", "Dressed but never alive.", "Associated with fashion."]),

  // ===== FOOD =====
  W("pizza", "easy", ["Associated with parties.", "People argue about toppings.", "Delivered to your door.", "A universal crowd-pleaser."]),
  W("burger", "easy", ["Associated with fast food.", "American classic.", "Messy to eat.", "Comes with a side usually."]),
  W("ice cream", "easy", ["Associated with summer treats.", "Melts fast.", "Children love it.", "A reward food."]),
  W("chocolate", "easy", ["Associated with cravings.", "A common gift.", "Linked to guilty pleasure.", "Melts in your hands."]),
  W("popcorn", "easy", ["Associated with entertainment.", "Gets stuck in your teeth.", "A salty or sweet debate.", "Made for sharing, or not."]),
  W("sandwich", "easy", ["Associated with packed lunches.", "Quick and convenient.", "Endless combinations.", "Held in hands."]),
  W("pancakes", "easy", ["Associated with slow weekend mornings.", "Stacked high.", "Toppings matter.", "A breakfast indulgence."]),
  W("noodles", "easy", ["Associated with student life.", "Slurping is acceptable.", "Quick comfort food.", "Comes in many forms."]),
  W("cake", "easy", ["Associated with celebrations.", "Candles might be involved.", "People fight over the corner piece.", "The centerpiece of parties."]),
  W("coffee", "easy", ["Associated with mornings.", "People can't function without it.", "A daily ritual.", "Bitter but beloved."]),
  W("sushi", "medium", ["Associated with a specific country.", "An acquired taste.", "Eaten with special tools.", "Fancy but divisive."]),
  W("taco", "medium", ["Associated with a specific cuisine.", "Messy by design.", "A weekly tradition for some.", "Crunch or softness is debated."]),
  W("salad", "medium", ["Associated with diets.", "The healthy choice.", "Often disappointing.", "Ordered to feel less guilty."]),
  W("pancake cereal", "hard", ["A viral trend.", "Tiny versions of something familiar.", "More effort than it's worth.", "Internet fame."]),
  W("fondue", "hard", ["Associated with dipping.", "A communal experience.", "Retro dinner parties.", "Everyone shares one pot."]),
  W("burrito", "medium", ["Wrapped up tight.", "Associated with a specific cuisine.", "Falls apart at the end.", "Portable and filling."]),
  W("cereal", "easy", ["Associated with breakfast in a rush.", "Eaten dry by chaotic people.", "The box art used to matter.", "Gets soggy fast."]),
  W("bubble tea", "medium", ["Chewy surprises inside.", "Associated with younger generations.", "Very photogenic.", "A drink and a snack in one."]),
  W("instant ramen", "medium", ["Associated with being broke.", "College survival food.", "Ready in minutes.", "Sodium overload."]),
  W("croissant", "medium", ["Associated with a European country.", "Flaky and buttery.", "A fancy breakfast.", "Crumbs everywhere."]),

  // ===== ANIMALS =====
  W("dog", "easy", ["Man's best friend.", "Associated with loyalty.", "People take it for walks.", "It gets excited about everything."]),
  W("cat", "easy", ["Associated with independence.", "It ignores you on purpose.", "The internet's favorite.", "Judges you silently."]),
  W("elephant", "easy", ["It never forgets.", "Associated with safaris.", "Big ears.", "Gentle giant."]),
  W("shark", "easy", ["Associated with fear of the ocean.", "A famous movie villain.", "It never stops moving.", "Teeth are the famous part."]),
  W("penguin", "easy", ["Associated with formal wear jokes.", "Waddles around.", "Lives in the cold.", "Very photogenic."]),
  W("monkey", "easy", ["Associated with mischief.", "Similar to us.", "Steals from tourists.", "Swings around."]),
  W("horse", "easy", ["Associated with riding.", "Races are famous.", "A rich person's hobby.", "Historic transportation."]),
  W("lion", "easy", ["King of something.", "Associated with pride.", "The mane is iconic.", "Lazy most of the day."]),
  W("dolphin", "easy", ["Associated with intelligence.", "Playful in the water.", "Does tricks.", "Always looks happy."]),
  W("snake", "easy", ["Associated with fear.", "No legs but still fast.", "Sheds regularly.", "A common phobia."]),
  W("spider", "easy", ["Eight of something.", "Associated with fear.", "Builds something beautiful.", "Appears unexpectedly in bathrooms."]),
  W("bee", "easy", ["Associated with summer picnics.", "Makes something sweet.", "Misunderstood as aggressive.", "Essential for the planet."]),
  W("owl", "medium", ["Associated with wisdom.", "Active at night.", "Its head does something creepy.", "A symbol in stories."]),
  W("octopus", "medium", ["Associated with eight of something.", "Very intelligent.", "An escape artist.", "Changes to hide."]),
  W("camel", "medium", ["Associated with harsh environments.", "Stores something famous.", "Grumpy reputation.", "A desert icon."]),
  W("koala", "medium", ["Sleeps most of the day.", "Associated with a specific country.", "Looks cuddly but isn't friendly.", "Holds onto things."]),
  W("sloth", "medium", ["Associated with laziness.", "Moves incredibly slowly.", "A modern internet icon.", "Hangs around all day."]),
  W("platypus", "hard", ["Associated with evolution jokes.", "Looks assembled from spare parts.", "Confuses scientists.", "From a specific country."]),
  W("chameleon", "hard", ["Associated with changing.", "Its eyes move independently.", "Blends in.", "Slow and deliberate."]),
  W("possum", "hard", ["Famous for pretending.", "Active at night.", "Underrated and misunderstood.", "Plays dead."]),

  // ===== ACTIVITIES =====
  W("swimming", "easy", ["Associated with summer.", "A full-body workout.", "Learned as a child.", "Involves a specific environment."]),
  W("dancing", "easy", ["Associated with parties.", "Rhythm is involved.", "Some people refuse to do it.", "Weddings require it."]),
  W("gaming", "easy", ["Associated with screens.", "People stay up too late doing it.", "Competitive versions exist.", "A modern obsession."]),
  W("sleeping", "easy", ["Nobody gets enough of it.", "Associated with dreams.", "The best part of the day for some.", "Done daily, hopefully."]),
  W("travelling", "easy", ["Associated with adventure.", "People save money for it.", "Photos are mandatory.", "Broadens the mind."]),
  W("cooking", "easy", ["Associated with home.", "Some love it, some fear it.", "A daily necessity for many.", "Follows instructions, or not."]),
  W("shopping", "easy", ["Associated with spending money.", "A weekend activity.", "Therapy for some.", "Malls revolve around it."]),
  W("running", "easy", ["Associated with early mornings.", "People train for events.", "Free but painful.", "A love-hate activity."]),
  W("camping", "easy", ["Associated with the outdoors.", "Sleeping somewhere uncomfortable.", "Fires are involved.", "Bugs are part of the deal."]),
  W("singing", "easy", ["Associated with showers.", "Karaoke nights.", "Some should never do it publicly.", "Done in cars with confidence."]),
  W("fishing", "medium", ["Associated with patience.", "Very slow-paced.", "An excuse for silence.", "Stories exaggerate results."]),
  W("yoga", "medium", ["Associated with calm.", "Flexibility is involved.", "Mat required.", "Breathing matters."]),
  W("hiking", "medium", ["Associated with nature trails.", "Boots are involved.", "Uphill struggles.", "The view is the reward."]),
  W("skiing", "medium", ["Associated with winter holidays.", "Expensive hobby.", "Snow required.", "Falling is part of learning."]),
  W("meditation", "medium", ["Associated with emptiness of mind.", "Sitting still is hard.", "Apps teach it now.", "Peace is the goal."]),
  W("surfing", "medium", ["Associated with a cool lifestyle.", "Waiting is most of it.", "A beach staple.", "Balance and patience."]),
  W("binge watching", "medium", ["Associated with whole weekends disappearing.", "Just one more episode.", "Streaming made it possible.", "Regret follows."]),
  W("doomscrolling", "hard", ["Associated with bad news.", "Thumbs get tired.", "Happens before bed.", "Time vanishes."]),
  W("gardening", "medium", ["Associated with patience and dirt.", "Retirement stereotype.", "Therapeutic for many.", "Slow rewards."]),
  W("thrifting", "medium", ["Associated with treasure hunting.", "Second-hand finds.", "Trendy again.", "Patience pays off."]),

  // ===== PROFESSIONS / PEOPLE =====
  W("teacher", "easy", ["Associated with chalk and patience.", "Underpaid but essential.", "Everyone remembers a good one.", "Shaping the future daily."]),
  W("doctor", "easy", ["Associated with white coats.", "Years of training.", "People lie to them sometimes.", "A trusted figure."]),
  W("police officer", "easy", ["Associated with authority.", "People feel nervous around them.", "Enforces rules.", "Sirens are related."]),
  W("chef", "easy", ["Associated with kitchens.", "A specific hat.", "Creative and stressed.", "TV loves them."]),
  W("pilot", "easy", ["Associated with the sky.", "A dream job for kids.", "Calm voices over speakers.", "Uniforms with stripes."]),
  W("firefighter", "easy", ["Associated with heroism.", "Runs toward danger.", "Red vehicles.", "Kids admire them."]),
  W("actor", "medium", ["Associated with fame.", "Pretends professionally.", "Rejection is constant.", "Red carpets involved."]),
  W("influencer", "medium", ["Associated with phones and rings of light.", "A modern career.", "Authenticity is debated.", "Content is everything."]),
  W("detective", "medium", ["Associated with mysteries.", "Notices small things.", "A classic fiction archetype.", "Asks uncomfortable questions."]),
  W("magician", "medium", ["Associated with deception.", "Nothing is as it seems.", "Sleight of hand.", "Never reveals secrets."]),
  W("janitor", "hard", ["Associated with invisible work.", "Cleans up after everyone.", "Underappreciated.", "Works when others leave."]),
  W("weather forecaster", "hard", ["Often wrong, never fired.", "Associated with maps on screens.", "People complain about them.", "Predictions are guesses."]),

  // ===== ABSTRACT / MIXED =====
  W("birthday", "easy", ["Associated with getting older.", "One per year.", "Cake and singing involved.", "Some people dread it."]),
  W("wedding", "easy", ["Associated with a big commitment.", "Expensive one-day event.", "Dancing and speeches.", "Family drama guaranteed."]),
  W("funeral", "medium", ["Associated with goodbyes.", "Dark clothing.", "Somber gatherings.", "A final ceremony."]),
  W("Christmas", "easy", ["Associated with December.", "Gifts and trees.", "Family gatherings.", "Songs everywhere."]),
  W("Halloween", "easy", ["Associated with costumes.", "End of October.", "Candy is essential.", "Fear is fun here."]),
  W("exam", "easy", ["Associated with stress.", "Studying all night.", "Results matter too much.", "Silence is enforced."]),
  W("job interview", "easy", ["Associated with nervousness.", "Dressed up for it.", "Rehearsed answers.", "First impressions matter."]),
  W("taxes", "medium", ["Associated with April stress.", "Nobody enjoys it.", "Certain in life.", "Paperwork nightmare."]),
  W("traffic jam", "medium", ["Associated with honking.", "Wasted time.", "City life reality.", "Horn symphony."]),
  W("black hole", "hard", ["Nothing escapes it.", "Associated with mystery.", "Physics breaks there.", "Invisible but powerful."]),
  W("déjà vu", "hard", ["Associated with strange familiarity.", "Your brain glitches.", "Happened just now.", "Unexplainable feeling."]),
  W("midlife crisis", "hard", ["Associated with buying something red.", "A certain age.", "Sudden life changes.", "Questioning everything."]),
];

module.exports = { WORDS };
